### ISSUE TITLE
No raids occurs

### ISSUE THREAD

**Issue by Sakamata927** [SmileycorpMC/raids-backport#11]
The raid event will not occur even if you enter the village with a bad omen attached.
[raids.log](https://github.com/user-attachments/files/15552137/raids.log)

**Comment by SmileycorpMC** [comment]
Apparently when updating I accidentally made the mod generate the default raid config in the wrong folder and didn't notice because my test instances still had the old config in them.
 

Updating to 1.1.3a and deleting the mods config folder should fix it.
