### ISSUE TITLE
Potential Issue with JEI and JustEnoughResources (Crashes on Startup and World Entry)

### ISSUE THREAD

**Issue by NikkeiZX** [SmileycorpMC/raids-backport#13]
So I've tried a few things, but I can't seem to get my game to boot with Raids Backport (v1.1.3) in my modpack. Originally it wouldn't even make it to the title screen and I'd get a crashlog (thanks to VanillaFix) claiming JEI (latest: 4.16.1.1012), JER [Just Enough Resources], and Raids were the culprits. I got rid of JER and am atleast able to make it to the title screen, but I get the same crash blaming Raids whenever I try to enter a world, new or old. Also, it happens regardless of Crossbow Backport being in or not. Is this a known issue, or is there anything in particular I need to do?

 

This is the crashlog on OpenEye With JER, stopping me form reaching the title screen:
https://openeye.openmods.info/crashes/b43ef950a696f1756f0a1fa06889392f

 

This is the crashlog on OpenEye Without JER when entering a world: 
https://openeye.openmods.info/crashes/b33d2b8abe0959bf552500ae4089a401

**Comment by SmileycorpMC** [comment]
Do you have spartan's weaponry installed?

**Comment by NikkeiZX** [comment]
Yes, I have it installed with a few Spartan addons

**Comment by SmileycorpMC** [comment]
Which version do you have installed?

**Comment by NikkeiZX** [comment]
Ah, turns out I had a very old version of Spartan's (v1.3.8). I hadn't realized I was so behind on versions. Sorry about that! I'm now using 1.5.3, switched Better Combat to RL Craft, and everything works with Raids now. Thanks!

**Comment by SmileycorpMC** [comment]
I may need to add something to the mod page, or some kind of version check.
