### ISSUE TITLE
Crash with Improved Villagers: Organized Combat

### ISSUE THREAD

**Issue by darkheadmaster132** [SmileycorpMC/raids-backport#15]
just like the title says

**Comment by SmileycorpMC** [comment]
Can you send the crash report it generates?

**Comment by darkheadmaster132** [comment]
[crash-2024-07-30_19.11.25-client.txt](https://github.com/user-attachments/files/16431328/crash-2024-07-30_19.11.25-client.txt)

**Comment by SmileycorpMC** [comment]
Should be fixed in 1.1.3a
