### ISSUE TITLE
Once the attack begins, TPS drops to 0 and all entities are frozen.

### ISSUE THREAD

**Issue by blueshadowlaser2023** [SmileycorpMC/raids-backport#3]
NO Log error or crash report, the game just frozen when the raid is began. I use the newest version 1.1.1

**Comment by SmileycorpMC** [comment]
Do you have the raids.log file from when it froze?

**Comment by blueshadowlaser2023** [comment]
Oh, I didn't save the raids.log , But just have a glance, it's only one line, just like "Loaded outpost spawn entity EntityPillager*(1-1):1 as net.smileycorp.raids.common.entities.EntityPillager with weight 1". I guess because miss spartans weaponry, or I install the plugin of tinkers construct 2: Tinkers' Evolution and PlusTiC.  There is no more information at the last.log.

**Comment by blueshadowlaser2023** [comment]
Use 1.1.0 Successfully triggered the attack，the raids.log is "Adding entity EntityVindicator ..." at the second line.
So I guess some EntityVindicator would adding just frozen the game when I use 1.1.1 triggered the attack.

**Comment by blueshadowlaser2023** [comment]
When the game frozen, I see some EntityPillager but haven't weapon in hand.

**Comment by SmileycorpMC** [comment]
I'm assuming in that case there may be some broken nbt data on crossbows they're spawned with, I'll look into it and see if I can reproduce it.

**Comment by SmileycorpMC** [comment]
Should be fixed in 1.1.2
