### ISSUE TITLE
Pillagers don't fire at the player with any weapon

### ISSUE THREAD

**Issue by AnxiousRexy** [SmileycorpMC/raids-backport#4]

**Comment by SmileycorpMC** [comment]
What mods do you have installed?

Them shooting has been working for me.

**Comment by AnxiousRexy** [comment]
> What mods do you have installed?
> 
> Them shooting has been working for me.

I tried without mods, They do shoot. Idk why its like that tbh but my last crash report lists my mod list.

**Comment by Grizdor** [comment]
I think I have the same issue.

- With only **Raids Backport 1.1.2** :
Pillagers shoot me like intended with the vanilla bow.

- With only **Raids Backport 1.1.2** and **Crossbows Backport 1.1.0b** :
Pillagers don't shoot me with their crossbows. But they still doing the charging crossbow animation continuously even if they don't shoot with it. If I let a pillager with a bow in the world before adding Crossbows Backport it don't shoot with the bow either.

**Comment by ZajiShinobi2** [comment]
I have the same issue. But the problem is in the updated versions of this mod. In the 1.1.0 they shoot normally. Even if i have mods installed. Maybe that's a clue to fix the problem. Sorry if my english is bad.

**Comment by Carvercarver1** [comment]
Same. Could it be something related to the AI or the lack of ammo or reload script not resulting it?

**Comment by SmileycorpMC** [comment]
fixed in 1.1.3
