### ISSUE TITLE
Pillagers in survival crashes the game if it detected any modded crossbows

### ISSUE THREAD

**Issue by AnxiousRexy** [SmileycorpMC/raids-backport#5]

**Comment by SmileycorpMC** [comment]
Can you send the crash report?

**Comment by AnxiousRexy** [comment]
[crash-2024-04-27_15.41.18-client.txt](https://github.com/SmileycorpMC/raids-backport/files/15139620/crash-2024-04-27_15.41.18-client.txt)

**Comment by AnxiousRexy** [comment]
> Can you send the crash report?

[crash-2024-04-27_15.41.18-client.txt](https://github.com/SmileycorpMC/raids-backport/files/15139625/crash-2024-04-27_15.41.18-client.txt)

**Comment by SmileycorpMC** [comment]
Should be fixed in 1.1.2.
