### ISSUE TITLE
Incompatibility issues with Electrobob's Wizardry 

### ISSUE THREAD

**Issue by Coder-Relri** [SmileycorpMC/raids-backport#6]
The latest version of this mod seems to be making the trades for the Wizard Mobs from Electrobob's Wizardry disappear.

I'm currently using:
-Raids-Backport-1.1.1
-ElectrobobsWizardry-4.3.13
-Forge-14.23.5.2860

**Comment by Coder-Relri** [comment]
Sorry for coming back to this but since it hasn't received any comments, is this an issue regarding ElectrobobsWizardry and must be reported to them or this mod? I'm assuming it's due to this mod since trades were working fine without this mod.

**Comment by SmileycorpMC** [comment]
fixed in 1.1.3
