### ISSUE TITLE
Incompatibility Issue with Xyn

### ISSUE THREAD

**Issue by Coder-Relri** [SmileycorpMC/raids-backport#7]
When trying to boot up minecraft with Xyn downloaded, it crashes during the start up process and returns the error "java.lang.NoClassDefFoundError: net/smileycorp/raids/common/entities/EntityPillager".

I'm currently using: 
-Forge-14.23.5.2860
-Raids-Backport-1.1.1
-Nyx SLY-1.4.3 (https://www.curseforge.com/minecraft/mc-mods/xyn-fork/files/4492129)

[latest.log](https://github.com/SmileycorpMC/raids-backport/files/15043089/latest.log)

**Comment by SmileycorpMC** [comment]
Reinstall both mods, I can't reproduce this crash.

**Comment by SmileycorpMC** [comment]
Do you have any other mods or just those?

**Comment by Coder-Relri** [comment]
That's odd, I had tested it with the mods alone and I managed to reproduce the error. I'll try to test again at some point tomorrow. Maybe the issue could also stem from me using the ROTN version of Nyx with the Xyn mod, but I can't remember.

**Comment by Coder-Relri** [comment]
Never mind, I realised my mistake with this issue, it was due to me accidentally installing the original NYX and the fork of it in the same modpack that was causing the problem. Sorry for the inconvenience.

**Comment by SmileycorpMC** [comment]
No problem, it's always worth checking if it is a bug with the mod or not.
